In [41]:
import numpy as np
import pandas as pd

### Load Data

In [42]:
data = pd.read_csv("/content/sample_data/student_learning_air_quality.csv")

In [43]:
data.head()

,student_id,day,period,subject,grade,age,has_asthma,co2_ppm,pm25_ugm3,temperature_c,humidity_pct,air_quality_label,quiz_score,reaction_time_ms,focus_rating,error_rate,heart_rate_bpm,cognitive_impairment,performance_label
0,STU0001,Friday,1st Period,Mathematics,Grade 11,14,1,504.4,8.61,21.3,45.3,Good,74.9,245,8.2,1.59,67,0.0108,Medium
1,STU0005,Friday,1st Period,Mathematics,Grade 8,15,0,542.6,8.58,21.0,42.0,Good,58.8,238,5.9,2.47,75,0.0121,Low
2,STU0006,Friday,1st Period,Mathematics,Grade 9,12,0,541.2,8.05,20.8,44.4,Good,81.0,203,7.8,0.41,75,0.0195,High
3,STU0011,Friday,1st Period,Mathematics,Grade 9,17,1,525.9,8.56,20.5,44.4,Good,74.2,206,6.8,1.11,80,0.0200,Medium
4,STU0012,Friday,1st Period,Mathematics,Grade 11,17,0,529.3,7.23,20.3,44.4,Good,58.5,240,6.6,2.16,77,0.0106,Low

In [44]:
data.tail()

,student_id,day,period,subject,grade,age,has_asthma,co2_ppm,pm25_ugm3,temperature_c,humidity_pct,air_quality_label,quiz_score,reaction_time_ms,focus_rating,error_rate,heart_rate_bpm,cognitive_impairment,performance_label
1995,STU0189,Wednesday,5th Period,English,Grade 9,13,0,737.5,10.94,21.7,48.9,Moderate,75.5,220,6.5,1.27,77,0.0422,Medium
1996,STU0192,Wednesday,5th Period,English,Grade 10,16,0,722.9,12.10,21.6,47.2,Moderate,62.2,263,5.3,2.01,72,0.1099,Medium
1997,STU0195,Wednesday,5th Period,English,Grade 9,12,0,734.9,13.22,21.4,49.0,Moderate,54.6,277,5.3,2.06,80,0.1081,Low
1998,STU0197,Wednesday,5th Period,English,Grade 7,12,0,728.3,12.58,22.0,47.4,Moderate,48.1,266,7.5,1.90,85,0.0915,Low
1999,STU0198,Wednesday,5th Period,English,Grade 11,12,0,721.7,11.38,21.3,48.5,Moderate,58.2,239,7.3,1.94,71,0.0737,Low

In [45]:
data.describe()

,age,has_asthma,co2_ppm,pm25_ugm3,temperature_c,humidity_pct,quiz_score,reaction_time_ms,focus_rating,error_rate,heart_rate_bpm,cognitive_impairment
count,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.00000,2000.00000,2000.000000,2000.000000
mean,14.590000,0.112000,632.76675,9.287365,21.204450,46.77585,65.244150,236.562000,7.12525,1.58896,73.768500,0.038318
std,1.790671,0.315445,92.57236,2.217145,0.756195,3.20481,12.509847,22.258951,1.25500,0.69261,4.209842,0.041622
min,12.000000,0.000000,450.70000,4.450000,19.100000,36.40000,26.700000,177.000000,3.50000,0.00000,59.000000,0.010100
25%,13.000000,0.000000,542.47500,7.690000,20.700000,44.40000,56.575000,221.000000,6.20000,1.13000,71.000000,0.013800
50%,15.000000,0.000000,643.60000,9.010000,21.200000,47.10000,65.100000,235.000000,7.10000,1.60000,74.000000,0.017150
75%,16.000000,0.000000,705.72500,10.630000,21.700000,49.20000,73.800000,250.000000,8.00000,2.06000,77.000000,0.052600
max,17.000000,1.000000,830.50000,15.900000,23.400000,55.00000,100.000000,318.000000,10.00000,3.90000,88.000000,0.201100

In [46]:
data.isnull().sum()

student_id              0
day                     0
period                  0
subject                 0
grade                   0
age                     0
has_asthma              0
co2_ppm                 0
pm25_ugm3               0
temperature_c           0
humidity_pct            0
air_quality_label       0
quiz_score              0
reaction_time_ms        0
focus_rating            0
error_rate              0
heart_rate_bpm          0
cognitive_impairment    0
performance_label       0
dtype: int64

### Filter Data and Group By

In [47]:
data_filter = data[(data['age'] > 16) & (data['quiz_score'] > 80)]

In [48]:
data_filter

,student_id,day,period,subject,grade,age,has_asthma,co2_ppm,pm25_ugm3,temperature_c,humidity_pct,air_quality_label,quiz_score,reaction_time_ms,focus_rating,error_rate,heart_rate_bpm,cognitive_impairment,performance_label
20,STU0062,Friday,1st Period,Mathematics,Grade 11,17,0,558.6,7.72,21.0,44.7,Good,100.0,206,10.0,0.00,79,0.0192,High
38,STU0112,Friday,1st Period,Mathematics,Grade 11,17,0,540.3,7.25,20.9,43.9,Good,88.0,210,9.5,0.56,75,0.0104,High
47,STU0148,Friday,1st Period,Mathematics,Grade 8,17,0,530.2,7.71,21.0,48.0,Good,81.1,204,8.9,0.48,69,0.0190,High
52,STU0157,Friday,1st Period,Mathematics,Grade 11,17,0,516.4,7.41,20.5,45.8,Good,83.0,225,9.2,1.07,67,0.0145,High
64,STU0193,Friday,1st Period,Mathematics,Grade 8,17,0,538.4,7.75,20.3,41.8,Good,95.5,193,9.4,0.49,70,0.0189,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1722,STU0098,Wednesday,2nd Period,Physics,Grade 8,17,0,565.6,7.84,21.3,48.0,Good,90.9,236,9.3,0.55,69,0.0108,High
1752,STU0166,Wednesday,2nd Period,Physics,Grade 10,17,0,531.0,6.38,21.7,46.4,Good,81.8,240,9.2,0.81,76,0.0107,High
1794,STU0062,Wednesday,3rd Period,Biology,Grade 11,17,0,631.5,8.59,21.6,43.4,Good,94.6,220,9.4,0.00,77,0.0192,High
1809,STU0098,Wednesday,3rd Period,Biology,Grade 8,17,0,651.4,8.90,21.4,44.7,Good,89.2,209,10.0,0.00,71,0.0108,High
1875,STU0062,Wednesday,4th Period,History,Grade 11,17,0,681.9,7.91,20.8,52.4,Good,90.0,213,10.0,0.00,71,0.0192,High

In [49]:
data_group_by_subject = data.groupby('subject').size()

In [50]:
data_group_by_subject

subject
Biology        406
English        386
History        397
Mathematics    406
Physics        405
dtype: int64

In [51]:
data_group_by_age = data.groupby('age').size()

In [52]:
data_group_by_age

age
12    357
13    305
14    298
15    309
16    303
17    428
dtype: int64

In [53]:
data_group_by_age_quiz = data.groupby(['age', 'quiz_score']).size()

In [54]:
data_group_by_age_quiz

age  quiz_score
12   34.7          1
     35.5          1
     36.6          1
     37.3          1
     37.9          1
                  ..
17   94.6          2
     95.4          1
     95.5          1
     97.5          1
     100.0         3
Length: 1443, dtype: int64

### ML Fundamental

### Supervised Learning

In supervised learning model learns form the labeled data. where input data provided with labeled and the correct answers. Model learns pattern between data and corrects data and predicts on the new data.

Example:

Predict house price, property price

Loan approval

Email Spam detection

Classification problems

Algorithm used in the Supervised Learning:

Linear Regression

Logistic Regression

Decisions Tree

Random Forest

SVM

### Unsupervised Learning

Unsupervised learning data has no labels. It learns form the pattern, sequences, hidden pattern and structures.

Examples:

Detecting anomalies

Recomendation system

Segmentation pattern

Algorithm used in Unsupervised learning:

K-means clustering

DBSCAN

Hierachecal Clustering

<h3>Train Test Split</h3>
<p>Machine learns patterns, structre from data. and also memorise the also. That's why model should test with the unseen data so that model can understand actual patterns from the data.</p>

<h4>Training Set</h4>
<p>Maximum size of the data gives the model to train by finding patters, structure, sequeces and others.
Models need maximum to maximum data for the betters results. A common structure in the train and test set 80% of data gives the models as training data</p>

<h4>Test Set</h4>
<p>Some data for evaluate the models perfomance. Common structure is 20% data gives the models for evaluate the models perfomance.</p>

In [57]:
# Split the train and test data in 80% and 20%
from sklearn.model_selection import train_test_split

In [ ]:
x = train_data
y = test_data
x_train, x_test, y_train,y_test = train_test_split(x,y,test_size=0.2)

<h3>Overfitting</h3>
<p>Models learns from patterns. if the data has noise,random then models learns from that data. As a result - During training time accuracy is high.
- During testing accuracy is lower the expected and poor.
</p>
<p>There are 3 types of Fitting</p>
<ul>
  <li>Good Fit</li>
  <li>Overfit</li>
  <li>Underfit</li>
</ul>

When there is more then 10% difference in the traing and testing then it consider as overfit.

<h3>Scikit-learn Classifier</h3>

In [58]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [59]:
# Load Data
dataset = load_iris()

x = dataset.data
y = dataset.target

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [60]:
model = RandomForestClassifier(random_state=42)

In [61]:
model.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [62]:
y_pred = model.predict(x_test)

In [63]:
accuracy = accuracy_score(y_test, y_pred)

In [64]:
print("Accuracy is ", accuracy)
print("Report of classfication")
print(classification_report(y_test,y_pred))

Accuracy is  0.9666666666666667
Report of classfication
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.92      0.96        13
           2       0.88      1.00      0.93         7

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30